#
# https://kubernetes.io/docs/concepts/configuration/secret/
#
---
apiVersion: v1
kind: Secret
metadata:
  name: mlflow-minio-secret
  namespace: mlflow
type: Opaque
stringData:
  AccessKeyID: admin
  SecretKey: minio-D0408AC0
